server:
  port: 8002
spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://192.168.1.101:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1
  config-center:
    address: zookeeper://192.168.1.101:2181
    timeout: 60000
  metadata-report:
    address: zookeeper://192.168.1.101:2181
    timeout: 60000
  provider:
    timeout: 30000

zookeeper:
  #每次重试时间间隔，单位毫秒
  baseSleepTimeMs: 1000
  #重试次数
  maxRetries: 3
  #zookeeper服务连接id与端口
  connectString: 192.168.1.101:2181
  #会话超时时间，单位毫秒
  sessionTimeoutMs: 5000
  #连接创建超时时间，单位毫秒
  connection-timeout-ms: 5000