server:
  port: 8002
spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://192.168.1.101:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1
  config-center:
    address: zookeeper://192.168.1.101:2181
    timeout: 60000
  metadata-report:
    address: zookeeper://192.168.1.101:2181
    timeout: 60000