server:
  port: 8000

spring:
  application:
    name: hf-demo
  main:
    allow-bean-definition-overriding: true
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 192.168.1.101:26379
        - 192.168.1.101:26380
        - 192.168.1.101:26381
      password: xhf0724.
    password: xhf0724.
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 10
    client-type: lettuce