server:
  port: 8001
spring:
  application:
    name: dubbo-consumer
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://localhost:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1
  config-center:
    address: zookeeper://localhost:2181
    timeout: 60000
  metadata-report:
    address: zookeeper://localhost:2181
    timeout: 60000
  scan:
    base-packages: com.hf.provider.service
  consumer:
    check: false