server:
  port: 8001
spring:
  application:
    name: hf-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.101}:${MYSQL_PORT:3306}/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:xhf0724.}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 如果是空对象的时候,不抛异常
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      # 反序列化的时候如果多了其他属性,不抛出异常
      FAIL_ON_UNKNOWN_PROPERTIES: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

